---
- hosts       : all
  become      : yes

  gather_facts: False
  pre_tasks   :
    - name        : Install python for Ansible
      raw         : test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - setup: # aka gather_facts

  tasks       :
    - include: tasks/common.yml
    - include: tasks/java.yml
    - include: tasks/node.yml
    - include: tasks/postgres.yml
    - include: tasks/stubby.yml
